format = """
[î‚¶](#32302f)\
$os\
$username\
[î‚°](bg:#504945 fg:#32302f)\
$directory\
[î‚°](fg:#504945 bg:#928374)\
$git_branch\
$git_status\
[î‚°](fg:#928374 bg:#7c6f64)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[î‚°](fg:#7c6f64 bg:#8ec07c)\
$docker_context\
[î‚°](fg:#8ec07c bg:#a89984)\
$time\
[î‚° ](fg:#a89984)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#32302f"
style_root = "bg:#32302f"
format = '[ à¼¼ ã¤ â—•_â—• à¼½ã¤ ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
symbol = "à¼¼ ã¤ â—•_â—• à¼½ã¤ "
style = "bg:#b16286"
disabled = true # Disabled by default
format = '[ $symbol ($version) ]($style)'

[directory]
style = "bg:#504945"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#689d6a"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#928374"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#928374"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "ğŸ’¤ "
style = "bg:#7c6f64"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#a89984"
format = '[ â”»â”â”» $time ]($style)'

